export const labelMessages = {
    lbl: {
        type: ' Type',
        audience: 'Audience',
        eventtype: 'Event Type',
        startdate: 'Event Starting On',
        previous: 'Previous',
        next: 'Next',
        search: 'Search',
        changefilters: 'Change Filter',
        reset: 'Reset',
        apply: 'Apply',
        by: 'by',
        datetime: 'Event Date and Time',
        join: 'Join',
        online: 'Online',
        offline: 'Offline',
        pages:'Pages',
        collaborators: 'Collaborators',
        dialcode:'Dial Code',
        onlineproviderdata: 'Online Provider Data',
        provider:'Provider',
        createnewevent:'Create New Event',
        startdatetime:'Start Date and Time',
        enddatetime:'End Date and Time',
        registrationstartdate:'Registration Start Date',
        registrationenddate:'Registration End Date',
        save:'Save',
        cancel:'Cancel',
        edit:'Edit',
        retire:'Retire',
        enroll:'Enroll',
        unenroll:'Unenroll',
        month: "Month",
        week: "Week",
        day: "Day",
        today: "Today",
        myEvents:'My events',
        myImages:'My Images',
        allImages:'All Images',
        selectImage:'Select Image',
        uploadAndUse:'Upload And Use',
        chooseAndDragImage:'Choose or drag and drop your image here*',
        uploadFromComputer:'Upload from Computer',
        uploadImageTypes:'Upload png, jpeg (Max File size: 1MB)',
        allowedImageTypes:'Allowed file types are: png, jpeg',
        maximumAllowedSize:'Maximum allowed file size: 1MB',
        copyright:'Copyright & License*',
        termsAndConditions:'I understand and confirm that all resources and assets created through the content editor or uploaded on the platform shall be available for free and public use without limitations on the platform (web portal, applications and any other end user interface that the platform would enable) and will be licensed under terms & conditions and policy guidelines of the platform. In doing so, the copyright and license of the original author is not infringed.',
        DropAndChoose:'Drop or choose file to upload before entering the details',
        back:'Back',
        searchingthis:'Searching this',
        Searching:'Searching',
        iconlabel:'Icon label',
        addImage:'Add Image',
        // createnewevent:'Create',
        // createnewevent:'Create',
        // createnewevent:'Create',
    }
};
