 export const urlConfig = {
     selectlang:"en",
    // endpoint configs...!
    // URLs...!
    eventDetailApi :  "assets/api/event-detail.json",
    eventListApi : "assets/api/eventlist.json",
    eventCreateApi: "https://jsonplaceholder.typicode.com/posts",
    eventFormConfigApi : "assets/api/event-create.json",
    eventFilterConfigApi: "assets/api/event-filter.json",
    enrollListApi : "assets/api/enroll-list.json",
    myEvents: "assets/api/myeventlist.json",
    enrollApi: "v1/event/enroll",
    // URLs...!
    detail :  "assets/api/event-detail.json",
    // detail :  "https://igot-sunbird.idc.tarento.com/api/event/v4/read/",
    list : "assets/api/eventlist.json",
    create: "https://igot-sunbird.idc.tarento.com/api/event/v4/create",
    update: "https://igot-sunbird.idc.tarento.com/api/event/v4/update",
    formConfig : "assets/api/event-create.json",
    enrolllist : "assets/api/enroll-list.json",
    enroll: "https://igot-sunbird.idc.tarento.com/v1/event/enroll",
    unEnroll:"https://igot-sunbird.idc.tarento.com/v1/event/unenroll",
    retire : "https://igot-sunbird.idc.tarento.com/private/event/v4/retire",
    publish: "https://igot-sunbird.idc.tarento.com/event/v4/publish",
    ImageSearchApi :  "assets/api/search-images.json",
    EditModeApi :  "assets/api/editmode.json",
    createImage:"content/v3/create",
    calenderevent:"assets/api/eventlist_new.json",
    search:"/v3/search",
};
