 export const urlConfig = {
    // endpoint configs...!
    // URLs...!
    // eventDetailApi :  "assets/api/event-detail.json",
    eventListApi : "assets/api/eventlist.json",
    eventCreateApi: "https://jsonplaceholder.typicode.com/posts",
    eventFormConfigApi : "assets/api/event-create.json",
    eventFilterConfigApi: "assets/api/event-filter.json",
    enrollListApi : "assets/api/enrolled-events.json",
    myEvents: "assets/api/myeventlist.json",
    enrollApi: "v1/event/enroll",
    usersApi: "assets/api/users.json",
    participantsList: "assets/api/participants.json",
    // URLs...!
    // detail :  "/event/v4/read/do_11334351316861747212",
    // detail :  "/event/v4/read/",
    // detail :  "https://igot-sunbird.idc.tarento.com/api/event/v4/read/",
    detail : "assets/api/event-detail.json",
    list : "assets/api/eventlist.json",
    create: "/event/v4/create",
    update: "/event/v4/update",
    formConfig : "assets/api/event-create.json",
    enrolllist : "assets/api/enrolled-events.json",
    // enrolllist : "assets/api/enroll-list.json",
    enroll: "https://igot-sunbird.idc.tarento.com/v1/event/enroll",
    retire : "https://igot-sunbird.idc.tarento.com/private/event/v4/retire",
    // publish: "https://igot-sunbird.idc.tarento.com/event/v4/publish",
    publish: "/event/v4/publish",
    calenderevent:"assets/api/eventlist_new.json",
    ImageSearchApi :  "assets/api/search-images.json",
    EditModeApi :  "assets/api/editmode.json",
    createImage:"content/v3/create",
    // BBBGetUrl:"assets/api/BBBCreatEvent.json",
    BBBGetUrl:"event/v4/join"
};
